//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerJannersten.UI.Resources.Localization.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdditionalSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdditionalSetting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PerJannersten.UI.Resources.Localization.Pages.AdditionalSetting", typeof(AdditionalSetting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show names.
        /// </summary>
        internal static string all_rounds {
            get {
                return ResourceManager.GetString("all_rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required player ID.
        /// </summary>
        internal static string all_rounds_required_player_id {
            get {
                return ResourceManager.GetString("all_rounds_required_player_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rounds.
        /// </summary>
        internal static string all_rounds_show_names {
            get {
                return ResourceManager.GetString("all_rounds_show_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM.
        /// </summary>
        internal static string com {
            get {
                return ResourceManager.GetString("com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string com_required {
            get {
                return ResourceManager.GetString("com_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until rd.
        /// </summary>
        internal static string com_untilrd {
            get {
                return ResourceManager.GetString("com_untilrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each deal.
        /// </summary>
        internal static string each_deal {
            get {
                return ResourceManager.GetString("each_deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending board order.
        /// </summary>
        internal static string each_deal_abo {
            get {
                return ResourceManager.GetString("each_deal_abo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal entry after play.
        /// </summary>
        internal static string each_deal_deap {
            get {
                return ResourceManager.GetString("each_deal_deap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string each_deal_feedback {
            get {
                return ResourceManager.GetString("each_deal_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own result.
        /// </summary>
        internal static string each_deal_feedback_own_result {
            get {
                return ResourceManager.GetString("each_deal_feedback_own_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify TD of no play.
        /// </summary>
        internal static string each_deal_ntonp {
            get {
                return ResourceManager.GetString("each_deal_ntonp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send contract separately.
        /// </summary>
        internal static string each_deal_scs {
            get {
                return ResourceManager.GetString("each_deal_scs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate lead.
        /// </summary>
        internal static string each_deal_vl {
            get {
                return ResourceManager.GetString("each_deal_vl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game settings.
        /// </summary>
        internal static string game_settings {
            get {
                return ResourceManager.GetString("game_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorer.
        /// </summary>
        internal static string scorer {
            get {
                return ResourceManager.GetString("scorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masters.
        /// </summary>
        internal static string scorer_masters {
            get {
                return ResourceManager.GetString("scorer_masters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N &amp; E.
        /// </summary>
        internal static string scorer_ne {
            get {
                return ResourceManager.GetString("scorer_ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S &amp; E.
        /// </summary>
        internal static string scorer_se {
            get {
                return ResourceManager.GetString("scorer_se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TD.
        /// </summary>
        internal static string td {
            get {
                return ResourceManager.GetString("td", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent calls.
        /// </summary>
        internal static string td_silent_calls {
            get {
                return ResourceManager.GetString("td_silent_calls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Game Setting.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Additional Game Setting.
        /// </summary>
        internal static string title_default {
            get {
                return ResourceManager.GetString("title_default", resourceCulture);
            }
        }
    }
}
