//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerJannersten.UI.Resources.Localization.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Setting_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setting_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PerJannersten.UI.Resources.Localization.Pages.Setting.en", typeof(Setting_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for.
        /// </summary>
        internal static string ask_for {
            get {
                return ResourceManager.GetString("ask_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bidding.
        /// </summary>
        internal static string ask_for_bidding {
            get {
                return ResourceManager.GetString("ask_for_bidding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal.
        /// </summary>
        internal static string ask_for_deal {
            get {
                return ResourceManager.GetString("ask_for_deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ask_for_id {
            get {
                return ResourceManager.GetString("ask_for_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead.
        /// </summary>
        internal static string ask_for_lead {
            get {
                return ResourceManager.GetString("ask_for_lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        internal static string ask_for_pin {
            get {
                return ResourceManager.GetString("ask_for_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconfirm.
        /// </summary>
        internal static string ask_for_reconfirm {
            get {
                return ResourceManager.GetString("ask_for_reconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of round.
        /// </summary>
        internal static string end_of_round {
            get {
                return ResourceManager.GetString("end_of_round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit changes.
        /// </summary>
        internal static string end_of_round_permit {
            get {
                return ResourceManager.GetString("end_of_round_permit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play next info.
        /// </summary>
        internal static string end_of_round_play_next {
            get {
                return ResourceManager.GetString("end_of_round_play_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recap at end.
        /// </summary>
        internal static string end_of_round_recap_end {
            get {
                return ResourceManager.GetString("end_of_round_recap_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ranking.
        /// </summary>
        internal static string end_of_round_show_ranking {
            get {
                return ResourceManager.GetString("end_of_round_show_ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show summary.
        /// </summary>
        internal static string end_of_round_show_summary {
            get {
                return ResourceManager.GetString("end_of_round_show_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 10 only.
        /// </summary>
        internal static string end_of_round_top10 {
            get {
                return ResourceManager.GetString("end_of_round_top10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string feedback {
            get {
                return ResourceManager.GetString("feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each deal.
        /// </summary>
        internal static string feedback_each_deal {
            get {
                return ResourceManager.GetString("feedback_each_deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string feedback_each_deal_automatic {
            get {
                return ResourceManager.GetString("feedback_each_deal_automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        internal static string feedback_each_deal_contracts {
            get {
                return ResourceManager.GetString("feedback_each_deal_contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makable as.
        /// </summary>
        internal static string feedback_each_deal_makable {
            get {
                return ResourceManager.GetString("feedback_each_deal_makable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show deal.
        /// </summary>
        internal static string feedback_each_deal_show_deal {
            get {
                return ResourceManager.GetString("feedback_each_deal_show_deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show score.
        /// </summary>
        internal static string feedback_each_deal_show_score {
            get {
                return ResourceManager.GetString("feedback_each_deal_show_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traveller.
        /// </summary>
        internal static string feedback_each_deal_traveller {
            get {
                return ResourceManager.GetString("feedback_each_deal_traveller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricks.
        /// </summary>
        internal static string feedback_each_deal_tricks {
            get {
                return ResourceManager.GetString("feedback_each_deal_tricks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game &amp; scoring type.
        /// </summary>
        internal static string game_scoring_type {
            get {
                return ResourceManager.GetString("game_scoring_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttler.
        /// </summary>
        internal static string game_scoring_type_buttler {
            get {
                return ResourceManager.GetString("game_scoring_type_buttler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross IMPs.
        /// </summary>
        internal static string game_scoring_type_cross {
            get {
                return ResourceManager.GetString("game_scoring_type_cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        internal static string game_scoring_type_individual {
            get {
                return ResourceManager.GetString("game_scoring_type_individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP.
        /// </summary>
        internal static string game_scoring_type_mp {
            get {
                return ResourceManager.GetString("game_scoring_type_mp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairs.
        /// </summary>
        internal static string game_scoring_type_pairs {
            get {
                return ResourceManager.GetString("game_scoring_type_pairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string game_scoring_type_teams {
            get {
                return ResourceManager.GetString("game_scoring_type_teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More settings.
        /// </summary>
        internal static string more_settings {
            get {
                return ResourceManager.GetString("more_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score across the field.
        /// </summary>
        internal static string score_across_the_field {
            get {
                return ResourceManager.GetString("score_across_the_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings from.
        /// </summary>
        internal static string settings_from {
            get {
                return ResourceManager.GetString("settings_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string settings_from_default {
            get {
                return ResourceManager.GetString("settings_from_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring software.
        /// </summary>
        internal static string settings_from_scoring {
            get {
                return ResourceManager.GetString("settings_from_scoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show at start.
        /// </summary>
        internal static string show_at_start {
            get {
                return ResourceManager.GetString("show_at_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TD.
        /// </summary>
        internal static string td {
            get {
                return ResourceManager.GetString("td", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls by BT.
        /// </summary>
        internal static string td_calls_by_bt {
            get {
                return ResourceManager.GetString("td_calls_by_bt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On / off.
        /// </summary>
        internal static string td_calls_by_bt_on_off {
            get {
                return ResourceManager.GetString("td_calls_by_bt_on_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        internal static string td_pin {
            get {
                return ResourceManager.GetString("td_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timing.
        /// </summary>
        internal static string timing {
            get {
                return ResourceManager.GetString("timing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min for reg..
        /// </summary>
        internal static string timing_min {
            get {
                return ResourceManager.GetString("timing_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min/board.
        /// </summary>
        internal static string timing_min_board {
            get {
                return ResourceManager.GetString("timing_min_board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min/move.
        /// </summary>
        internal static string timing_min_move {
            get {
                return ResourceManager.GetString("timing_min_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use timer.
        /// </summary>
        internal static string timing_use_timer {
            get {
                return ResourceManager.GetString("timing_use_timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Settings.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Game Settings.
        /// </summary>
        internal static string title_default {
            get {
                return ResourceManager.GetString("title_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricks &amp; points.
        /// </summary>
        internal static string tricks_points {
            get {
                return ResourceManager.GetString("tricks_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declarer&apos;s points.
        /// </summary>
        internal static string tricks_points_declarer_points {
            get {
                return ResourceManager.GetString("tricks_points_declarer_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - / = / + (EUR).
        /// </summary>
        internal static string tricks_points_eur {
            get {
                return ResourceManager.GetString("tricks_points_eur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N scores.
        /// </summary>
        internal static string tricks_points_n_scores {
            get {
                return ResourceManager.GetString("tricks_points_n_scores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricks taken.
        /// </summary>
        internal static string tricks_points_tricks_taken {
            get {
                return ResourceManager.GetString("tricks_points_tricks_taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made / down (US).
        /// </summary>
        internal static string tricks_points_us {
            get {
                return ResourceManager.GetString("tricks_points_us", resourceCulture);
            }
        }
    }
}
